version: '3.8'
services:
  henk:
    image: ghcr.io/tintin10q/headless-henk:latest
    labels:
      - "com.centurylinklabs.watchtower.scope=headless-henkies"
    environment:
      - HTTP_PROXY=http://[IP]:10700
      - HTTPS_PROXY=http://[IP]:10700
      - no_proxy=chief.placenl.nl
    volumes:
      - ./henk01.toml:/workdir/accounts.toml
      - ./henk01:/cache
    command: --tokens_cache=/cache/tokens_cache.toml
    restart: always
  henk2:
    image: ghcr.io/tintin10q/headless-henk:latest
    labels:
      - "com.centurylinklabs.watchtower.scope=headless-henkies"
    environment:
      - HTTP_PROXY=http://[IP]:10701
      - HTTPS_PROXY=http://[IP]:10701
      - no_proxy=chief.placenl.nl
    volumes:
      - ./henk02.toml:/workdir/accounts.toml
      - ./henk02:/cache
    command: --tokens_cache=/cache/tokens_cache.toml
    restart: always
  henk3:
    image: ghcr.io/tintin10q/headless-henk:latest
    labels:
      - "com.centurylinklabs.watchtower.scope=headless-henkies"
    environment:
      - HTTP_PROXY=http://[IP]:10702
      - HTTPS_PROXY=http://[IP]:10702
      - no_proxy=chief.placenl.nl
    volumes:
      - ./henk03.toml:/workdir/accounts.toml
      - ./henk03:/cache
    command: --tokens_cache=/cache/tokens_cache.toml
    restart: always
  henk4:
    image: ghcr.io/tintin10q/headless-henk:latest
    labels:
      - "com.centurylinklabs.watchtower.scope=headless-henkies"
    environment:
      - HTTP_PROXY=http://[IP]:10703
      - HTTPS_PROXY=http://[IP]:10703
      - no_proxy=chief.placenl.nl
    volumes:
      - ./henk04.toml:/workdir/accounts.toml
      - ./henk04:/cache
    command: --tokens_cache=/cache/tokens_cache.toml
    restart: always
  henk5:
    image: ghcr.io/tintin10q/headless-henk:latest
    labels:
      - "com.centurylinklabs.watchtower.scope=headless-henkies"
    environment:
      - HTTP_PROXY=http://[IP]:10704
      - HTTPS_PROXY=http://[IP]:10704
      - no_proxy=chief.placenl.nl
    volumes:
      - ./henk05.toml:/workdir/accounts.toml
      - ./henk05:/cache
    command: --tokens_cache=/cache/tokens_cache.toml
    restart: always
  henk6:
    image: ghcr.io/tintin10q/headless-henk:latest
    labels:
      - "com.centurylinklabs.watchtower.scope=headless-henkies"
    environment:
      - HTTP_PROXY=http://[IP]:10705
      - HTTPS_PROXY=http://[IP]:10705
      - no_proxy=chief.placenl.nl
    volumes:
      - ./henk06.toml:/workdir/accounts.toml
      - ./henk06:/cache
    command: --tokens_cache=/cache/tokens_cache.toml
    restart: always